### ISSUE TITLE
Uploading with curl not working 

### ISSUE THREAD

**Issue by mohamedelhassak** [LiveUI/Boost#157]
Hi, I am trying to upload .apk file but it's not working 

This is what I get when executing curl command,

![image](https://user-images.githubusercontent.com/52533870/137304070-eac349c2-49c2-41c9-877c-76f2210ecc85.png)

**Comment by rafiki270** [comment]
Looks like you are hitting a frontend endpoint. The curl should be directed at the api

**Comment by mohamedelhassak** [comment]
Thanks !😁,

So, I try this,

curl    -X POST    -H "Authorization: Token [MY TOKEN]"  -d @facebook.apk    http://[API_IP]:[PORT]/apps

This is what I get,

![image](https://user-images.githubusercontent.com/52533870/137456654-5e6100d5-a23e-4014-a254-ebae444b1cf5.png)

NB: I did'nt any prefix So, I did'nt use APICORE_SERVER_PATH_PREFIX
