### ISSUE TITLE
Docker potrebuje nejaky persistent storage

### ISSUE THREAD

**Issue by rafiki270** [LiveUI/Boost#35]
V zakladu je potreba nekam lokalne ukladat data (appky) pokud nebude nastaveny S3 (nechci to na firmy nutit protoze nektery maj trosku problem s Amazonem)

Tzn, je potreba udelat nejaky Volume ... Boost budto muze dostat cestu pres `LOCAL_ROOT` a to kdyz neni tak to zkusi pouzit `HOME` nez to spadne ... veci co se rozbalujou a podobne sou v `/tmp/Boost/`

Jak tohle vyresime?

**Comment by Mikulas** [comment]
V samotném dockeru je to `docker run -v $HOST_DIR:$MOUNT_DIR` … liveui/boost`, tzn. je na uživateli jak to vyřeší, docker to jenom umožňuje mountnout. V k8s je to podobně, s tím že to umí automaticky vytvářet různé cloudové disky atp.

**Comment by rafiki270** [comment]
a `HOST_DIR` je environmental var co je dostupny i v appce nebo to bude to druhy?

**Comment by Mikulas** [comment]
To je ukázka, myslim tím, že je na tobě co tam nastavíš. Může to být třeba tohle:
`docker run -v /Users/rafiki/boost-storage:/tmp/Boost ... liveui/boost`

**Comment by rafiki270** [comment]
Jasny, dik
