### ISSUE TITLE
Upravit docker

### ISSUE THREAD

**Issue by rafiki270** [LiveUI/Boost#36]
Aby to pouzivalo public image co uz ma python a Javu ... Dockerfile v `/Docker/Base/Dockerfile`

Nejak nevim jak to nahostovat ... :( ... ale pokud by slo tak na LiveUI ucet u dockeru, ne manGoweb ...

**Comment by Mikulas** [comment]
Closed in https://github.com/LiveUI/Boost/compare/97a1f99...4246905
